$(document).ready(function(){
    $(".hidden").hide();
    $("#show").click(function(){
      $(".everything").hide();
      $(".content").hide();
      $(".hidden").show();
    });
    $("#hide").click(function(){
        $(".hidden").hide();
        $(".everything").show();
        $(".content").show();
    });
  });
