$(document).ready(function(){
    $("#show").click(function(){
      $(".hidden").show();
      console.log("hit");
    });
    $("#hide").click(function(){
        $(".hidden").hide();
    });
  });